### ISSUE TITLE
suggest disallowing underscores in file stub

### ISSUE THREAD

**Issue by qureshlatif** [mikemeredith/saveJAGS#2]
I was having trouble recovering my saves with the recoverSaves function. Turns out I had underscores in my file stub. Once I renamed my files so that there were no underscores in the file stub, I was able to recover the saves. It might be helpful to disallow underscores in the file stub or provide a warning when a file stub with an underscore is used.

**Comment by mikemeredith** [comment]
Thanks Quresh, that was a problem with early versions but I thought it had been fixed - obviously not! I'll take another look.

**Comment by mikemeredith** [comment]
Sorry for the delay Quresh. The old bug fixed was underscores in the folder name, but it didn't fix underscores in the actual file stub. That's now fixed in v. 0.0.3.9021.

**Comment by qureshlatif** [comment]
Great, thanks!

Sent from Yahoo Mail on Android 
 
  On Thu, May 7, 2020 at 8:56 PM, mikemeredith<notifications@github.com> wrote:   


Sorry for the delay Quresh. The old bug fixed was underscores in the folder name, but it didn't fix underscores in the actual file stub. That's now fixed in v. 0.0.3.9021.

**Comment by qureshlatif** [comment]
Hi there. I tried installing your newest version unsuccessfully. Apparently, I need the package "mcmcOutput" but this package does not appear to be available on CRAN.
    On Thursday, May 7, 2020, 08:56:13 PM MDT, mikemeredith <notifications@github.com> wrote:  
 
 


Closed #2.

**Comment by mikemeredith** [comment]
Sorry Quresh, we're in a transition period here: `mcmcOutput` is a package which a couple of others will use - it regroups functionality currently in those package - but need to make sure they work together before submitting to CRAN. It'll take a few more days.

In the meantime, you can install the devel version with `devtools::install_github("mikemeredith/mcmcOutput")`.

Don't be surprised though if there are changes to `mcmcOutput` and  maybe `saveJAGS` in the next few days.

**Comment by qureshlatif** [comment]
No problem. Thank you!

Sent from Yahoo Mail on Android 
 
  On Mon, May 11, 2020 at 7:18 PM, mikemeredith<notifications@github.com> wrote:   


Sorry Quresh, we're in a transition period here: mcmcOutput is a package which a couple of others will use - it regroups functionality currently in those package - but need to make sure they work together before submitting to CRAN. It'll take a few more days.

In the meantime, you can install the devel version with devtools::install_github("mikemeredith/mcmcOutput").

Don't be surprised though if there are changes to mcmcOutput and maybe saveJAGS in the next few days.
