### ISSUE TITLE
unclear where to find package mcmcOutput 

### ISSUE THREAD

**Issue by mikeroswell** [mikemeredith/saveJAGS#3]
Excited to try your packages! It took me a few minutes to determine that a missing dependence, `mcmcOutput`, was also a package only on your github, would be great to add to the readme and your [blogpost](http://mikemeredith.net/blog/2018/Intro_saveJAGS.htm) to install that package first.

**Comment by mikemeredith** [comment]
Thanks mikeroswell, you are quite right, now done. 

Just now in the middle of developing all this. The `mcmcOutput` package is still being modified (3 commits yesterday and I expect more new features today) and relevant bits of `saveJAGS` are also provisional.  Then I need to modify the devel version of `wiqid` package to use `mcmcOutput`, which may involve some modifications to `mcmcOutput`, then a round of beta testing before submitting `mcmcOutput` to CRAN.
