### ISSUE TITLE
warning on underscore in filestub

### ISSUE THREAD

**Issue by mikeroswell** [mikemeredith/saveJAGS#4]
Hi Mike,
Thanks for the really quick response last time. I'm stoked about your package. One more little thing that tripped me up: I was getting an error with `recoverSaves`, because my filestub included an "_".  This pops up because of line 9 in "recoverSaves.R" ` stubs <- sapply(strsplit(raw, "_"), function(x) x[1])`

I think it is fine to prohibit underscores in the filestub, but would be good to give a warning or even error in the `saveJAGS()` function, something like 

`if(grepl("_", fileStub)){ [your warning or error message telling user not to have "_" in filestub]}`

Thanks so much!

**Comment by mikemeredith** [comment]
Thanks for that report (or reminder maybe!) The previous issue was with underscore in the directory name, and I fixed that 2 yrs ago. Now fixed the issue with underscores in the actual file name, version 0.0.3.9021. Please check it out.

What won't work in `recoverSaves` is a file stub with just a folder name, ie, ending in "/", eg, `fileStub = "foo/"` and that now throws an error in `saveJAGS`.
