### ISSUE TITLE
saveJAGS compilation error

### ISSUE THREAD

**Issue by stegzzz** [mikemeredith/saveJAGS#5]
Running the following command:

> rw1<-saveJAGS{rjdata, myinits, parameters, modelFile, chains=1, sample2save=10, nsaves=3,  
> burnin=200, filestub='rwsaves/test2') 

produces:
> rw1
> $AA
> [1] Error in rjags::jags.model(modelFile,data,initList, n.chains=chains, : \n
> RUNTIME ERROR Compilation error on line 4 unknown function RW
> attr(,"class")
> [1] try-error
> attr(,"condition")
> <simpleError in rjags::jags.model(modelFile,data,initList, n.chains=chains,n.adapt=0):
> RUNTIME ERROR Compilation error on line 4 unknown function RW

The function RW is a custom function loaded with rjags load.module command. The function works OK using standard rjags.

Using:
R 3.4.4
rjags 4-10
Ubuntu 18.04.4
JAGS 4.3.0

**Comment by mikemeredith** [comment]
Hi stegzzz,

Short answer is that if you want to load JAGS modules you need to include `modules = "whatever"` in the call to `saveJAGS`. Worth a try, but I think that will only work for the standard modules that come with JAGS.

This will involve an upgrade. We will likely have to pass the full path to the DLL to each of the workers. Doh, just realised DLLs are a Windows thing, will have to check  on other platforms! Can you give me the R code you used to load the module in `rjags`?

Thanks.

**Comment by stegzzz** [comment]
Hi Mike, the r-code to load my module was simply load.module('AssociativeModelModuleRW') which is an rjags function that loads the 'dll' AssociativeModelModuleRW.so and makes available the function RW. If you've got an idea how to make that function visible to the saveJAGS code I can try it out again but unfortunately my module is only compiled for linux -- I tried to do for windows too but the messy cross-platformery got the better of me.

I *think* all modules are default looked for by load.module in the same directory (e.g. on my windows machine JAGS-4.3.0/x64/modules where you will find e.g. mix.dll, dic.dll etc.) and that is where my module lives so hopefully a full path won't be needed.

BW, Steve

**Comment by mikemeredith** [comment]
Hi Steve, 

You can check which modules are in the default module location: do `library(rjags)` then do

 `dir(options("jags.moddir")[[1]])`

That should work on all platforms, I've tested on Ubuntu, Mac, Windows.

If your module is there, you should only have to add `modules = "AssociativeModelModuleRW"` to the call to `saveJAGS`, as it says in the help file for `saveJAGS`. Internally, `saveJAGS` calls `rjags::load.module` to load these.  Please *try* that and if it doesn't work let me have the error message and the output of `sessionInfo()`.

Thanks, Mike

**Comment by stegzzz** [comment]
That worked fine Mike, thanks for taking the time to advise, nice utility too!
BW, Steve
