### ISSUE TITLE
summary function

### ISSUE THREAD

**Issue by qureshlatif** [mikemeredith/saveJAGS#7]
This is not an issue per se, but not sure how else to communicate this. I have written a function that provides a summary table from saveJAGS output. In case it seems useful, I thought I'd share. I have included it in my personal R package with some documentation: https://github.com/qureshlatif/QSLpersonal/blob/master/R/sumJAGS.R

**Comment by mikemeredith** [comment]
Hi Quresh, Thanks for that! `saveJAGS` now uses the `mcmcOutput` package and allows results to be read in directly to an `mcmcOutput` object, which has summary and plotting methods plus a `sumryList` function, which produces a list of summary tables for each parameter. These only allow for one credible  interval (plus the median), perhaps we should allow more.

Regards, Mike

**Comment by qureshlatif** [comment]
OK, great! I will check that out. Thanks!
